### ISSUE TITLE
icon在项目哪里

### ISSUE THREAD

**Issue by PengMengShan** [rcyj-FED/vue3-composition-admin#40]

**Comment by PengMengShan** [comment]
我要添加图标，怎么添加进行，在项目中看到<svg/> 使用，没有找到在哪里可以添加图标，能和我说说吗

**Comment by RainManGO** [comment]
项目使用iconfont sysmbol。 为了调式方便没有下载，在html里面，可以替换成自己的。

**Comment by RainManGO** [comment]
如果想加入演示iconfont项目,留下iconfont 账号，我拉你进去。

**Comment by PengMengShan** [comment]
感谢

**Comment by PengMengShan** [comment]
这个 多了一个空格或者多了个分号就会报错，这个是在哪里设置了什么吗，太严格了

**Comment by PengMengShan** [comment]
这个eslintrc太严格了，我都试了好多关闭方法都没关闭掉，这个该如何关闭
